### PR TITLE
no need for slash when defining the url name

### PR DESCRIPTION
**Pull request by erlichmen**

### CODE REVIEW

**Comment by erlichmen** [comment]
Bump
Can you please merge it.

**Comment by jtnord** [comment]
@erlichmen this plugin has been superseeded by [dockerhub-notification-plugin](https://github.com/jenkinsci/dockerhub-notification-plugin) which uses the correct github api and integrates better with other Docker plugins.

**Comment by erlichmen** [comment]
@jtnord AFAICT dockerhub-notification-plugin contains the same bug, you need to remove the slash in the getUrlName() method.

**Comment by jtnord** [comment]
@erlichmen the slash is required as this action is only served from the root of Jenkins.

From the [javadoc Action.getUrlName()](http://javadoc.jenkins-ci.org/hudson/model/Action.html#getUrlName%28%29)

> If the returned string starts with '/', like '/foo', then it's assumed to be relative to the context path of the Jenkins webapp.

If you are seeing an issue around this then please file a [JIRA](https://issues.jenkins-ci.org) in the [dockerhub-notification-plugin](https://issues.jenkins-ci.org/secure/IssueNavigator.jspa?reset=true&jqlQuery=project+%3D+JENKINS+AND+component+%3D+dockerhub-notification-plugin) as to me the code looks correct, and as it is working for most people - it would at first glance seem like an issue with your environment/setup.

**Comment by erlichmen** [comment]
The [whoAmI](https://github.com/jenkinsci/jenkins/blob/84c76253862a2f36f813a7aa45b77d99c1616be4/core/src/main/java/hudson/security/WhoAmI.java)  (internal Core Jenkins action) handler doesn't have a slash, none of the extensions that implement UnprotectedRootAction.getUrlName() has a slash infont of them. 
[The code that validates unprotected root action](https://github.com/jenkinsci/jenkins/blob/fd42e33d619597ee4f3e7648792f4541ad6cc089/core/src/main/java/jenkins/model/Jenkins.java#L3826)  adds the slashs explictly when comparing.  
When you enable Jenkins security this plugin is just not going to work, doing a POST will return 403.  
If anything the document are incorrect on this matter.

**Comment by jtnord** [comment]
see [dockerhub-notification-plugin#2](https://github.com/jenkinsci/dockerhub-notification-plugin/pull/2) and [jenkins#1726](https://github.com/jenkinsci/jenkins/pull/1726)

**Comment by erlichmen** [comment]
great, thanks.

**Pull request closed without merging**
